# Generated by Django 5.0.1 on 2026-01-14 18:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('outlining', 'Outlining'), ('writing', 'Writing'), ('editing', 'Editing'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('chroma_collection_name', models.CharField(editable=False, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_word_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novel_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('brainstorm', 'Brainstorm'), ('plot', 'Plot Generation'), ('character', 'Character Creation'), ('outline', 'Outline Creation'), ('chapter', 'Chapter Writing'), ('edit', 'Editing'), ('score', 'Scoring')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage 0-100')),
                ('progress_message', models.CharField(blank=True, max_length=255)),
                ('input_data', models.JSONField(default=dict)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='novels.novelproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('protagonist', 'Protagonist'), ('antagonist', 'Antagonist'), ('mentor', 'Mentor'), ('sidekick', 'Sidekick'), ('love_interest', 'Love Interest'), ('supporting', 'Supporting'), ('minor', 'Minor')], max_length=20)),
                ('age', models.CharField(blank=True, max_length=50)),
                ('background', models.TextField(blank=True)),
                ('personality', models.TextField(blank=True)),
                ('motivation', models.TextField(blank=True)),
                ('flaw', models.TextField(blank=True)),
                ('arc', models.TextField(blank=True, help_text='Character development arc')),
                ('appearance', models.TextField(blank=True)),
                ('relationships', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='novels.novelproject')),
            ],
            options={
                'ordering': ['role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChapterOutline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('pov', models.CharField(blank=True, help_text='Point of view', max_length=255)),
                ('setting', models.CharField(blank=True, max_length=255)),
                ('events', models.TextField(help_text='What happens in this chapter')),
                ('character_development', models.TextField(blank=True)),
                ('pacing', models.CharField(choices=[('slow', 'Slow'), ('medium', 'Medium'), ('fast', 'Fast')], default='medium', max_length=10)),
                ('story_beats', models.TextField(blank=True, help_text='Major plot points')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_outlines', to='novels.novelproject')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chapter_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Full chapter content')),
                ('summary', models.TextField(blank=True)),
                ('word_count', models.IntegerField(default=0)),
                ('language', models.CharField(default='English', max_length=50)),
                ('writing_style', models.CharField(default='literary', max_length=50)),
                ('version', models.IntegerField(default=1)),
                ('is_draft', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outline', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapter', to='novels.chapteroutline')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='novels.novelproject')),
            ],
            options={
                'ordering': ['chapter_number'],
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premise', models.TextField(help_text='One-paragraph premise')),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('themes', models.TextField(blank=True, help_text='Main themes, comma-separated')),
                ('conflict', models.TextField(blank=True, help_text='Central conflict')),
                ('structure', models.TextField(blank=True, help_text='Three-act structure details')),
                ('arc', models.TextField(blank=True, help_text='Story arc overview')),
                ('tone', models.CharField(blank=True, max_length=100)),
                ('target_audience', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plot', to='novels.novelproject')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('time_period', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('culture', models.TextField(blank=True)),
                ('technology', models.TextField(blank=True)),
                ('politics', models.TextField(blank=True)),
                ('economy', models.TextField(blank=True)),
                ('important_locations', models.TextField(blank=True)),
                ('atmosphere', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='novels.novelproject')),
            ],
            options={
                'ordering': ['-is_primary', 'location'],
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_good', models.BooleanField(help_text='True for good example, False for bad')),
                ('category', models.CharField(choices=[('writing', 'General Writing'), ('dialogue', 'Dialogue'), ('description', 'Description'), ('exposition', 'Exposition'), ('action', 'Action'), ('pacing', 'Pacing')], max_length=50)),
                ('content', models.TextField()),
                ('description', models.TextField(help_text='Why this is a good/bad example')),
                ('issues', models.JSONField(blank=True, default=list, help_text='List of issues')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_good', 'category'], name='novels_exam_is_good_2fbd3c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='novelproject',
            index=models.Index(fields=['user', '-updated_at'], name='novels_nove_user_id_baf70c_idx'),
        ),
        migrations.AddIndex(
            model_name='generationtask',
            index=models.Index(fields=['project', '-created_at'], name='novels_gene_project_7859cc_idx'),
        ),
        migrations.AddIndex(
            model_name='generationtask',
            index=models.Index(fields=['celery_task_id'], name='novels_gene_celery__93100a_idx'),
        ),
        migrations.AddIndex(
            model_name='character',
            index=models.Index(fields=['project', 'role'], name='novels_char_project_d5048a_idx'),
        ),
        migrations.AddIndex(
            model_name='chapteroutline',
            index=models.Index(fields=['project', 'number'], name='novels_chap_project_9d5f20_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chapteroutline',
            unique_together={('project', 'number')},
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['project', 'chapter_number'], name='novels_chap_project_99b082_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('project', 'chapter_number', 'version')},
        ),
    ]
