# Generated by Django 5.0.1 on 2026-01-16 01:00

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIPerformanceMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_type', models.CharField(choices=[('brainstorm', 'Idea Generation'), ('plot', 'Plot and Characters Generation'), ('outline', 'Outlines Generation'), ('chapter', 'Chapter Generation')], db_index=True, max_length=20)),
                ('duration_seconds', models.FloatField(help_text='How long the API call took in seconds')),
                ('input_params', models.JSONField(blank=True, default=dict, help_text='e.g., num_chapters, word_count')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('success', models.BooleanField(default=True, help_text='Whether the API call succeeded')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['api_type', '-created_at'], name='novels_apip_api_typ_3bbb01_idx')],
            },
        ),
    ]
