# Generated by Django 5.0.1 on 2026-01-17 01:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0002_apiperformancemetric"),
    ]

    operations = [
        # Step 1: Rename the existing 'genre' CharField to 'genre_text' to preserve data
        migrations.RenameField(
            model_name="novelproject",
            old_name="genre",
            new_name="genre_text",
        ),
        migrations.RenameField(
            model_name="plot",
            old_name="genre",
            new_name="genre_text",
        ),
        # Step 2: Create Genre model
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name_key",
                    models.CharField(
                        help_text="Translation key for genre (e.g., 'fantasy', 'sci_fi')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this genre is publicly available",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["name_key"],
                "indexes": [
                    models.Index(
                        fields=["public"], name="novels_genr_public_a34fc4_idx"
                    )
                ],
            },
        ),
        # Step 3: Create GenreTranslation model
        migrations.CreateModel(
            name="GenreTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        choices=[("en", "English"), ("zh-hans", "Simplified Chinese")],
                        max_length=10,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Translated genre name", max_length=100),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="novels.genre",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["language_code"], name="novels_genr_languag_6600f5_idx"
                    )
                ],
                "unique_together": {("genre", "language_code")},
            },
        ),
        # Step 4: Add new 'genre' ForeignKey field
        migrations.AddField(
            model_name="novelproject",
            name="genre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="novels.genre",
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="genre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plots",
                to="novels.genre",
            ),
        ),
    ]
