# Generated by Django 5.0.1 on 2026-01-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_rename_genre_to_genre_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelproject',
            name='genre_text',
            field=models.CharField(blank=True, help_text='Legacy genre text - will be migrated to Genre model', max_length=100),
        ),
        migrations.AlterField(
            model_name='plot',
            name='genre_text',
            field=models.CharField(blank=True, help_text='Legacy genre text - will be migrated to Genre model', max_length=100),
        ),
    ]
