# Generated by Django 5.0.1 on 2026-01-17 06:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0004_alter_novelproject_genre_text_alter_plot_genre_text"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExampleScore",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "weight",
                    models.IntegerField(
                        help_text="Weight percentage for this category (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Score for this category (0-10)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category__order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ScoreCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (can be any language)", max_length=100
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this category is publicly available",
                    ),
                ),
                (
                    "default_weight",
                    models.IntegerField(
                        default=0,
                        help_text="Default weight percentage for this category",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order for system categories"
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True for system-defined categories",
                    ),
                ),
                (
                    "name_key",
                    models.CharField(
                        blank=True,
                        help_text="Translation key for system categories (e.g., 'story_plot')",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Score categories",
                "ordering": ["-is_system", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ScoreCategoryTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        choices=[("en", "English"), ("zh-hans", "Simplified Chinese")],
                        max_length=10,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Translated category name", max_length=100
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="example",
            name="genre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="examples",
                to="novels.genre",
            ),
        ),
        migrations.AddField(
            model_name="example",
            name="public",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether this example is publicly available",
            ),
        ),
        migrations.AddIndex(
            model_name="example",
            index=models.Index(
                fields=["public", "user"], name="novels_exam_public_1b021b_idx"
            ),
        ),
        migrations.AddField(
            model_name="examplescore",
            name="example",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scores",
                to="novels.example",
            ),
        ),
        migrations.AddField(
            model_name="scorecategory",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this category (NULL for system categories)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="score_categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="examplescore",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="novels.scorecategory"
            ),
        ),
        migrations.AddField(
            model_name="scorecategorytranslation",
            name="category",
            field=models.ForeignKey(
                limit_choices_to={"is_system": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="novels.scorecategory",
            ),
        ),
        migrations.AddIndex(
            model_name="scorecategory",
            index=models.Index(
                fields=["public", "created_by"], name="novels_scor_public_9d0daf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scorecategory",
            index=models.Index(
                fields=["is_system"], name="novels_scor_is_syst_680768_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examplescore",
            unique_together={("example", "category")},
        ),
        migrations.AddIndex(
            model_name="scorecategorytranslation",
            index=models.Index(
                fields=["language_code"], name="novels_scor_languag_f3c52d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scorecategorytranslation",
            unique_together={("category", "language_code")},
        ),
    ]
