# Generated by Django 5.0.1 on 2026-01-17 15:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0005_examplescore_scorecategory_scorecategorytranslation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="novelproject",
            unique_together={("user", "title")},
        ),
    ]
