# Generated by Django data migration

from django.db import migrations
from django.core.management import call_command


def seed_genres(apps, schema_editor):
    """Seed default genres with translations."""
    # Import the Genre and GenreTranslation models from the migration state
    Genre = apps.get_model('novels', 'Genre')
    GenreTranslation = apps.get_model('novels', 'GenreTranslation')

    genres_data = [
        {
            'name_key': 'fantasy',
            'translations': {
                'en': 'Fantasy',
                'zh-hans': '奇幻'
            }
        },
        {
            'name_key': 'science_fiction',
            'translations': {
                'en': 'Science Fiction',
                'zh-hans': '科幻'
            }
        },
        {
            'name_key': 'romance',
            'translations': {
                'en': 'Romance',
                'zh-hans': '言情'
            }
        },
        {
            'name_key': 'mystery',
            'translations': {
                'en': 'Mystery',
                'zh-hans': '悬疑'
            }
        },
        {
            'name_key': 'thriller',
            'translations': {
                'en': 'Thriller',
                'zh-hans': '惊悚'
            }
        },
        {
            'name_key': 'horror',
            'translations': {
                'en': 'Horror',
                'zh-hans': '恐怖'
            }
        },
        {
            'name_key': 'historical_fiction',
            'translations': {
                'en': 'Historical Fiction',
                'zh-hans': '历史小说'
            }
        },
        {
            'name_key': 'literary_fiction',
            'translations': {
                'en': 'Literary Fiction',
                'zh-hans': '文学小说'
            }
        },
        {
            'name_key': 'young_adult',
            'translations': {
                'en': 'Young Adult',
                'zh-hans': '青少年'
            }
        },
        {
            'name_key': 'adventure',
            'translations': {
                'en': 'Adventure',
                'zh-hans': '冒险'
            }
        },
        {
            'name_key': 'dystopian',
            'translations': {
                'en': 'Dystopian',
                'zh-hans': '反乌托邦'
            }
        }
    ]

    for genre_data in genres_data:
        # Create genre (get_or_create to avoid duplicates)
        genre, created = Genre.objects.get_or_create(
            name_key=genre_data['name_key'],
            defaults={'public': True}
        )

        # Create translations
        for lang_code, translation_name in genre_data['translations'].items():
            GenreTranslation.objects.get_or_create(
                genre=genre,
                language_code=lang_code,
                defaults={'name': translation_name}
            )


def reverse_seed_genres(apps, schema_editor):
    """Remove seeded genres."""
    Genre = apps.get_model('novels', 'Genre')
    GenreTranslation = apps.get_model('novels', 'GenreTranslation')

    # Only delete genres that were seeded (have name_key matching our seeds)
    seeded_keys = [
        'fantasy', 'science_fiction', 'romance', 'mystery', 'thriller',
        'horror', 'historical_fiction', 'literary_fiction', 'young_adult',
        'adventure', 'dystopian'
    ]

    Genre.objects.filter(name_key__in=seeded_keys).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0006_alter_novelproject_unique_together'),
    ]

    operations = [
        migrations.RunPython(seed_genres, reverse_seed_genres),
    ]
