# Generated by Django 5.0.1 on 2026-01-17 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0007_seed_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationtask',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='novels.novelproject'),
        ),
        migrations.AlterField(
            model_name='generationtask',
            name='task_type',
            field=models.CharField(choices=[('brainstorm', 'Brainstorm'), ('plot', 'Plot Generation'), ('character', 'Character Creation'), ('outline', 'Outline Creation'), ('chapter', 'Chapter Writing'), ('edit', 'Editing'), ('score', 'Scoring'), ('example_scoring', 'Example Scoring')], max_length=20),
        ),
    ]
