# Generated by Django 5.0.1 on 2026-01-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0008_alter_generationtask_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='category',
            field=models.CharField(blank=True, choices=[('writing', 'General Writing'), ('dialogue', 'Dialogue'), ('description', 'Description'), ('exposition', 'Exposition'), ('action', 'Action'), ('pacing', 'Pacing')], max_length=50, null=True),
        ),
    ]
