# Generated by Django 5.0.1 on 2026-01-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0009_alter_example_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='category',
            field=models.CharField(blank=True, choices=[('opening', 'Opening'), ('dialogue', 'Dialogue'), ('description', 'Description'), ('action', 'Action'), ('transition', 'Transition'), ('ending', 'Ending')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='description',
            field=models.TextField(blank=True, help_text='Why this is a good/bad example'),
        ),
    ]
