# Generated by Django 5.0.1 on 2026-01-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0010_alter_example_category_alter_example_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='locale',
            field=models.CharField(choices=[('English', 'English'), ('Chinese', 'Chinese'), ('French', 'French'), ('Spanish', 'Spanish'), ('German', 'German'), ('Japanese', 'Japanese')], default='English', help_text='Language of the content', max_length=50),
        ),
        migrations.AddField(
            model_name='example',
            name='title',
            field=models.CharField(blank=True, help_text='Short one-line summary of the example', max_length=200),
        ),
    ]
