# Generated by Django 5.0.1 on 2026-01-19 18:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0012_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('act_number', models.IntegerField(help_text='Act number (1, 2, or 3)')),
                ('subject', models.CharField(choices=[('SETUP', 'Setup'), ('CONFRONTATION', 'Confrontation'), ('RESOLUTION', 'Resolution')], help_text='Act type (SETUP, CONFRONTATION, RESOLUTION)', max_length=50)),
                ('percentage', models.IntegerField(help_text='Percentage of story (typically 25%, 50%, 25%)')),
                ('description', models.TextField(help_text='Detailed description of what happens in this act')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='novels.plot')),
            ],
            options={
                'ordering': ['act_number'],
            },
        ),
        migrations.AddField(
            model_name='chapteroutline',
            name='act',
            field=models.ForeignKey(blank=True, help_text='Act this outline belongs to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlines', to='novels.act'),
        ),
        migrations.AddIndex(
            model_name='act',
            index=models.Index(fields=['plot', 'act_number'], name='novels_act_plot_id_7101af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='act',
            unique_together={('plot', 'act_number')},
        ),
    ]
