# Generated by Django data migration

from django.db import migrations


def seed_score_categories(apps, schema_editor):
    """Seed default score categories with translations."""
    ScoreCategory = apps.get_model('novels', 'ScoreCategory')
    ScoreCategoryTranslation = apps.get_model('novels', 'ScoreCategoryTranslation')

    categories_data = [
        {
            'name_key': 'story_plot',
            'name': 'Story/Plot',
            'default_weight': 30,
            'order': 1,
            'translations': {
                'en': 'Story/Plot',
                'zh-hans': '故事/情节'
            }
        },
        {
            'name_key': 'character_development',
            'name': 'Character Development',
            'default_weight': 20,
            'order': 2,
            'translations': {
                'en': 'Character Development',
                'zh-hans': '角色发展'
            }
        },
        {
            'name_key': 'world_building',
            'name': 'World-Building / Setting',
            'default_weight': 15,
            'order': 3,
            'translations': {
                'en': 'World-Building / Setting',
                'zh-hans': '世界构建/设定'
            }
        },
        {
            'name_key': 'writing_style',
            'name': 'Writing Style / Language',
            'default_weight': 20,
            'order': 4,
            'translations': {
                'en': 'Writing Style / Language',
                'zh-hans': '写作风格/语言'
            }
        },
        {
            'name_key': 'dialogue',
            'name': 'Dialogue & Interactions',
            'default_weight': 10,
            'order': 5,
            'translations': {
                'en': 'Dialogue & Interactions',
                'zh-hans': '对话与互动'
            }
        },
        {
            'name_key': 'emotional_impact',
            'name': 'Emotional Impact / Engagement',
            'default_weight': 5,
            'order': 6,
            'translations': {
                'en': 'Emotional Impact / Engagement',
                'zh-hans': '情感影响/参与度'
            }
        },
    ]

    for cat_data in categories_data:
        # Create category (get_or_create to avoid duplicates)
        category, created = ScoreCategory.objects.get_or_create(
            name_key=cat_data['name_key'],
            defaults={
                'name': cat_data['name'],
                'public': True,
                'is_system': True,
                'created_by': None,
                'default_weight': cat_data['default_weight'],
                'order': cat_data['order']
            }
        )

        # Create translations
        for lang_code, translation_text in cat_data['translations'].items():
            ScoreCategoryTranslation.objects.get_or_create(
                category=category,
                language_code=lang_code,
                defaults={'name': translation_text}
            )


def reverse_seed_score_categories(apps, schema_editor):
    """Remove seeded score categories."""
    ScoreCategory = apps.get_model('novels', 'ScoreCategory')

    # Only delete categories that were seeded (have name_key matching our seeds)
    seeded_keys = [
        'story_plot', 'character_development', 'world_building',
        'writing_style', 'dialogue', 'emotional_impact'
    ]

    ScoreCategory.objects.filter(name_key__in=seeded_keys).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0013_act_chapteroutline_act_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_score_categories, reverse_seed_score_categories),
    ]
