# Generated by Django 5.0.1 on 2026-01-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0014_seed_score_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapteroutline",
            name="pacing",
            field=models.CharField(
                choices=[("slow", "Slow"), ("medium", "Medium"), ("fast", "Fast")],
                default="medium",
                max_length=64,
            ),
        ),
    ]
