# Generated by Django 5.0.1 on 2026-01-20 05:52

from django.db import migrations, models
from decimal import Decimal


def populate_order_key(apps, schema_editor):
    """Populate order_key from number for existing outlines."""
    ChapterOutline = apps.get_model('novels', 'ChapterOutline')
    for outline in ChapterOutline.objects.all():
        outline.order_key = Decimal(str(outline.number))
        outline.save(update_fields=['order_key'])


def reverse_populate_order_key(apps, schema_editor):
    """Reverse migration - no action needed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0015_increase_pacing_field_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapteroutline",
            options={"ordering": ["order_key"]},
        ),
        migrations.AlterUniqueTogether(
            name="chapteroutline",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="chapteroutline",
            name="order_key",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                help_text="Ordering key for sorting (allows insertion between items)",
                max_digits=10,
            ),
        ),
        migrations.RunPython(populate_order_key, reverse_populate_order_key),
        migrations.AlterField(
            model_name="chapteroutline",
            name="number",
            field=models.IntegerField(help_text="Chapter number (display)"),
        ),
        migrations.AlterUniqueTogether(
            name="chapteroutline",
            unique_together={("project", "order_key")},
        ),
        migrations.AddIndex(
            model_name="chapteroutline",
            index=models.Index(
                fields=["project", "order_key"], name="novels_chap_project_1fc9f2_idx"
            ),
        ),
    ]
