# Generated by Django 5.0.1 on 2026-01-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0016_add_order_key_to_chapter_outline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapteroutline",
            name="order_key",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Ordering key for sorting (allows insertion between items)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
