# Generated by Django 5.0.1 on 2026-01-20 19:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0018_add_user_prompt_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="novelproject",
            name="target_language",
            field=models.CharField(
                choices=[("en", "English"), ("zh-hans", "Simplified Chinese")],
                default="en",
                help_text="Target output language for AI generation",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="AgentRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_key",
                    models.CharField(
                        help_text="Unique identifier for this role",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "module_name",
                    models.CharField(
                        help_text="Associated module name", max_length=100
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this role is available"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name_key"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="novels_agen_is_acti_78faa0_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_key",
                    models.CharField(
                        help_text="Unique identifier for this policy",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("safety", "Safety"),
                            ("copyright", "Copyright"),
                            ("output", "Output Constraints"),
                            ("behavior", "Behavior Boundaries"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this policy is enforced"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Lower number = higher priority"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "System policies",
                "ordering": ["priority", "name_key"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "priority"],
                        name="novels_syst_is_acti_a7ca2c_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WritingStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_key",
                    models.CharField(
                        help_text="Unique identifier for this style", max_length=50
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="True for predefined system styles"
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this style is publicly available",
                    ),
                ),
                (
                    "pacing",
                    models.CharField(
                        choices=[
                            ("slow", "Slow"),
                            ("medium", "Medium"),
                            ("fast", "Fast"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("tone", models.CharField(blank=True, max_length=100)),
                (
                    "paragraph_length",
                    models.CharField(
                        choices=[
                            ("short", "Short"),
                            ("medium", "Medium"),
                            ("long", "Long"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "dialogue_ratio",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("cliffhanger_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this style (NULL for system styles)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="writing_styles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_system", "name_key"],
            },
        ),
        migrations.AddField(
            model_name="chapter",
            name="style_override",
            field=models.ForeignKey(
                blank=True,
                help_text="Override writing style for this chapter (uses project default if not set)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chapters_using",
                to="novels.writingstyle",
            ),
        ),
        migrations.AddField(
            model_name="chapteroutline",
            name="style_override",
            field=models.ForeignKey(
                blank=True,
                help_text="Override writing style for this chapter (uses project default if not set)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chapter_outlines_using",
                to="novels.writingstyle",
            ),
        ),
        migrations.AddField(
            model_name="novelproject",
            name="default_style",
            field=models.ForeignKey(
                blank=True,
                help_text="Default writing style for this project",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects_using",
                to="novels.writingstyle",
            ),
        ),
        migrations.CreateModel(
            name="WritingStyleTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        choices=[("en", "English"), ("zh-hans", "Simplified Chinese")],
                        max_length=10,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name in this language", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Style description"),
                ),
                (
                    "instructions",
                    models.TextField(help_text="Style-specific prompt instructions"),
                ),
                (
                    "style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="novels.writingstyle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WritingTechnique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_key",
                    models.CharField(
                        help_text="Unique identifier for this technique",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="True for predefined system techniques"
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this technique is publicly available",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("narrative", "Narrative"),
                            ("dialogue", "Dialogue"),
                            ("description", "Description"),
                            ("pacing", "Pacing"),
                            ("character", "Character Development"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this technique (NULL for system techniques)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="writing_techniques",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_system", "category", "name_key"],
            },
        ),
        migrations.AddField(
            model_name="novelproject",
            name="selected_techniques",
            field=models.ManyToManyField(
                blank=True,
                help_text="Writing techniques applied to this project",
                related_name="projects_using",
                to="novels.writingtechnique",
            ),
        ),
        migrations.CreateModel(
            name="WritingTechniqueTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        choices=[("en", "English"), ("zh-hans", "Simplified Chinese")],
                        max_length=10,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name in this language", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Technique description"),
                ),
                (
                    "instructions",
                    models.TextField(
                        help_text="Technique-specific prompt instructions"
                    ),
                ),
                (
                    "technique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="novels.writingtechnique",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AgentRoleTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        choices=[("en", "English"), ("zh-hans", "Simplified Chinese")],
                        max_length=10,
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        help_text="Role definition/system prompt in this language"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="novels.agentrole",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["language_code"], name="novels_agen_languag_0c5f8e_idx"
                    )
                ],
                "unique_together": {("role", "language_code")},
            },
        ),
        migrations.CreateModel(
            name="SystemPolicyTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        choices=[("en", "English"), ("zh-hans", "Simplified Chinese")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(help_text="Policy text in this language")),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="novels.systempolicy",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["language_code"], name="novels_syst_languag_2fe742_idx"
                    )
                ],
                "unique_together": {("policy", "language_code")},
            },
        ),
        migrations.AddIndex(
            model_name="writingstyle",
            index=models.Index(
                fields=["is_system", "public"], name="novels_writ_is_syst_8fb453_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="writingstyle",
            index=models.Index(
                fields=["created_by"], name="novels_writ_created_ebffc3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="writingstyle",
            unique_together={("name_key", "created_by")},
        ),
        migrations.AddIndex(
            model_name="writingstyletranslation",
            index=models.Index(
                fields=["language_code"], name="novels_writ_languag_0ad724_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="writingstyletranslation",
            unique_together={("style", "language_code")},
        ),
        migrations.AddIndex(
            model_name="writingtechnique",
            index=models.Index(
                fields=["is_system", "public"], name="novels_writ_is_syst_fd98e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="writingtechnique",
            index=models.Index(
                fields=["created_by"], name="novels_writ_created_7d772b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="writingtechnique",
            index=models.Index(
                fields=["category"], name="novels_writ_categor_642b59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="writingtechniquetranslation",
            index=models.Index(
                fields=["language_code"], name="novels_writ_languag_366b22_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="writingtechniquetranslation",
            unique_together={("technique", "language_code")},
        ),
    ]
