# Generated by Django 5.0.1 on 2026-01-21 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0019_add_prompt_architecture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plot",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="novelproject",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="example",
            name="genre",
        ),
        migrations.RemoveField(
            model_name="novelproject",
            name="genre_text",
        ),
        migrations.RemoveField(
            model_name="plot",
            name="genre_text",
        ),
        migrations.DeleteModel(
            name="GenreTranslation",
        ),
        migrations.DeleteModel(
            name="Genre",
        ),
    ]
