# Generated by Django 5.0.1 on 2026-01-26 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0023_remove_themes_and_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="act",
            field=models.ForeignKey(
                blank=True,
                help_text="Direct association with act (for chapters created without outline)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="direct_chapters",
                to="novels.act",
            ),
        ),
    ]
