# Generated by Django 5.0.1 on 2026-01-27 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0025_add_order_key_to_chapter'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chapter',
            new_name='novels_chap_project_7e6624_idx',
            old_name='chapter_project_order_idx',
        ),
    ]
