# Generated by Django 5.0.1 on 2026-01-28 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "novels",
            "0026_rename_chapter_project_order_idx_novels_chap_project_7e6624_idx",
        ),
    ]

    operations = [
        # Use SeparateDatabaseAndState because the table was already dropped
        # This only updates Django's model state without touching the database
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="chapter",
                    name="outline",
                ),
                migrations.DeleteModel(
                    name="ChapterOutline",
                ),
            ],
            database_operations=[
                # No database operations needed - table already doesn't exist
            ],
        ),
    ]
