# Generated by Django 5.0.1 on 2026-01-28 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0027_remove_chapter_outline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiperformancemetric',
            name='api_type',
            field=models.CharField(choices=[('brainstorm', 'Idea Generation'), ('plot', 'Plot and Characters Generation'), ('chapter', 'Chapter Generation')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='act',
            field=models.ForeignKey(blank=True, help_text='Direct association with act for chapter creation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_chapters', to='novels.act'),
        ),
        migrations.AlterField(
            model_name='generationtask',
            name='task_type',
            field=models.CharField(choices=[('brainstorm', 'Brainstorm'), ('plot', 'Plot Generation'), ('character', 'Character Creation'), ('chapter', 'Chapter Writing'), ('edit', 'Editing'), ('score', 'Scoring'), ('example_scoring', 'Example Scoring')], max_length=20),
        ),
    ]
