# Generated by Django 5.0.1 on 2026-01-28 21:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0028_alter_apiperformancemetric_api_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='novelproject',
            name='content_type',
            field=models.CharField(choices=[('novel', 'Novel'), ('poem', 'Poem'), ('essay', 'Essay'), ('sketch', 'Sketch'), ('article', 'News Article')], default='novel', help_text='Type of content this project will produce', max_length=20),
        ),
        migrations.CreateModel(
            name='ContentStructureTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('novel', 'Novel'), ('poem', 'Poem'), ('essay', 'Essay'), ('sketch', 'Sketch'), ('article', 'News Article')], help_text='Type of content this template is for', max_length=20)),
                ('name', models.CharField(help_text="Template name (e.g., 'Five-Paragraph Essay')", max_length=100)),
                ('is_system', models.BooleanField(default=False, help_text='System templates cannot be modified by users')),
                ('structure_data', models.JSONField(help_text="Template structure as JSON (e.g., {'sections': ['Introduction', 'Body', 'Conclusion']})")),
                ('description', models.TextField(blank=True, help_text="Description of this template's purpose")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this template (null for system templates)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structure_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['content_type', 'name'],
                'unique_together': {('content_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ContentPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Title of the content piece', max_length=255)),
                ('content', models.TextField(help_text='The actual poem/essay/sketch/article text')),
                ('word_count', models.IntegerField(default=0, help_text='Word count of the content')),
                ('sections_data', models.JSONField(default=dict, help_text="Content organized by sections (e.g., {'introduction': '...', 'body1': '...'})")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(help_text='The project this content belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='content_piece', to='novels.novelproject')),
                ('structure_template', models.ForeignKey(blank=True, help_text='Structure template used (for essays/sketches)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_pieces', to='novels.contentstructuretemplate')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentTypeCategoryWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(help_text='Weight/importance percentage for this category (e.g., 25 for 25%)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_weights', to='novels.scorecategory')),
            ],
            options={
                'ordering': ['-weight', 'category__name'],
            },
        ),
        migrations.CreateModel(
            name='ContentTypeScoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('novel', 'Novel'), ('poem', 'Poem'), ('essay', 'Essay'), ('sketch', 'Sketch'), ('article', 'News Article')], help_text='Content type this configuration is for', max_length=20, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score_categories', models.ManyToManyField(help_text='Score categories used for this content type', related_name='content_type_configs', through='novels.ContentTypeCategoryWeight', to='novels.scorecategory')),
            ],
            options={
                'verbose_name': 'Content Type Scoring Configuration',
                'verbose_name_plural': 'Content Type Scoring Configurations',
                'ordering': ['content_type'],
            },
        ),
        migrations.AddField(
            model_name='contenttypecategoryweight',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_weights', to='novels.contenttypescoringconfig'),
        ),
        migrations.AlterUniqueTogether(
            name='contenttypecategoryweight',
            unique_together={('config', 'category')},
        ),
    ]
