# Generated by Django 5.0.1 on 2026-01-29 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0029_novelproject_content_type_contentstructuretemplate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Idea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idea_data",
                    models.JSONField(
                        default=dict,
                        help_text="Original idea data (premise, theme, thesis, etc.)",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        help_text="Type of content (novel, poem, essay, sketch, article)",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        help_text="The project this idea belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idea",
                        to="novels.novelproject",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
