# Generated by Django 5.0.1 on 2026-01-30 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0030_idea"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="writingstyle",
            name="content_type",
            field=models.CharField(
                blank=True,
                help_text="Content type this style is designed for (blank for generic styles)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="writingstyle",
            index=models.Index(
                fields=["content_type"], name="novels_writ_content_831ea1_idx"
            ),
        ),
    ]
