# Generated by Django 5.0.1 on 2026-01-30 07:57

from django.db import migrations


def populate_content_type_styles(apps, schema_editor):
    """
    1. Update existing WritingStyles to have content_type='novel'
    2. Create 4 new content-type-specific styles with translations
    """
    WritingStyle = apps.get_model('novels', 'WritingStyle')
    WritingStyleTranslation = apps.get_model('novels', 'WritingStyleTranslation')

    # Step 1: Update existing styles to be novel-specific
    WritingStyle.objects.filter(is_system=True).update(content_type='novel')

    # Step 2: Create new content-type-specific styles
    styles_data = [
        {
            'name_key': 'poem',
            'content_type': 'poem',
            'pacing': 'slow',
            'tone': 'lyrical',
            'paragraph_length': 'short',
            'dialogue_ratio': 'low',
            'cliffhanger_enabled': False,
            'translations': {
                'en': {
                    'name': 'Poem Style',
                    'description': 'Lyrical and imagery-focused style for poetry creation',
                    'instructions': '''Focus on creating vivid imagery and sensory details that evoke emotion.

Key elements:
- Use concrete, specific images that appeal to the senses
- Pay attention to rhythm and musicality of language
- Employ metaphor, simile, and figurative language
- Consider line breaks and stanza structure for emphasis
- Create emotional resonance through word choice
- Use sound devices like alliteration, assonance, consonance when appropriate
- Build layers of meaning through imagery and symbolism
- Keep language precise and economical - every word should earn its place'''
                },
                'zh-hans': {
                    'name': '诗歌风格',
                    'description': '抒情性和意象为主的诗歌创作风格',
                    'instructions': '''专注于创造生动的意象和感官细节以唤起情感。

关键要素：
- 使用具体的、特定的意象来吸引感官
- 注意语言的节奏和音乐性
- 运用隐喻、明喻和比喻性语言
- 考虑断行和节结构以强调重点
- 通过词语选择创造情感共鸣
- 适当使用头韵、元音和辅音韵等声音手法
- 通过意象和象征建立多层含义
- 保持语言精确和简洁——每个词都应该发挥作用'''
                }
            }
        },
        {
            'name_key': 'essay',
            'content_type': 'essay',
            'pacing': 'medium',
            'tone': 'analytical',
            'paragraph_length': 'medium',
            'dialogue_ratio': 'low',
            'cliffhanger_enabled': False,
            'translations': {
                'en': {
                    'name': 'Essay Style',
                    'description': 'Analytical and structured style for essay writing',
                    'instructions': '''Develop a clear thesis and support it with logical argumentation and evidence.

Key elements:
- Begin with a strong thesis statement that makes a clear argument
- Organize ideas with topic sentences that support the thesis
- Use evidence, examples, and analysis to build your argument
- Address potential counterarguments to strengthen your position
- Maintain formal, academic tone while remaining engaging
- Use transitions to guide readers through your logic
- Build paragraphs around single, well-developed ideas
- Conclude by reinforcing your thesis and its implications
- Cite sources appropriately when using external evidence'''
                },
                'zh-hans': {
                    'name': '论文风格',
                    'description': '分析性和结构化的论文写作风格',
                    'instructions': '''发展一个清晰的论点，并用逻辑论证和证据来支持它。

关键要素：
- 以强有力的论点陈述开始，提出明确的论点
- 用支持论点的主题句组织想法
- 使用证据、例子和分析来构建你的论证
- 处理潜在的反驳论点以加强你的立场
- 保持正式的学术语气，同时保持吸引力
- 使用过渡词引导读者理解你的逻辑
- 围绕单一的、充分发展的想法构建段落
- 通过强化你的论点及其含义来总结
- 在使用外部证据时适当引用来源'''
                }
            }
        },
        {
            'name_key': 'sketch',
            'content_type': 'sketch',
            'pacing': 'medium',
            'tone': 'descriptive',
            'paragraph_length': 'medium',
            'dialogue_ratio': 'medium',
            'cliffhanger_enabled': False,
            'translations': {
                'en': {
                    'name': 'Sketch Style',
                    'description': 'Observational and descriptive style for literary sketches',
                    'instructions': '''Capture a moment, scene, or character with keen observation and vivid detail.

Key elements:
- Observe with precision - notice specific, concrete details
- Use sensory details to bring the scene to life (sight, sound, smell, texture)
- Capture the atmosphere and mood of the moment
- Include brief character observations or interactions that reveal personality
- Balance description with subtle reflection or insight
- Maintain a present, immediate quality - show what you're witnessing
- Keep the scope focused on a single moment or scene
- Let details speak for themselves without over-explaining
- End with a resonant image or observation that lingers'''
                },
                'zh-hans': {
                    'name': '速写风格',
                    'description': '观察性和描述性的文学速写风格',
                    'instructions': '''用敏锐的观察和生动的细节捕捉一个时刻、场景或人物。

关键要素：
- 精确观察——注意具体的、具体的细节
- 使用感官细节使场景生动起来（视觉、声音、气味、质感）
- 捕捉时刻的氛围和情绪
- 包括简短的人物观察或互动，揭示个性
- 平衡描述与微妙的反思或洞察
- 保持当下的、即时的品质——展示你正在目睹的内容
- 将范围集中在单一时刻或场景上
- 让细节自己说话，不要过度解释
- 以一个引人共鸣的意象或观察结束'''
                }
            }
        },
        {
            'name_key': 'article',
            'content_type': 'article',
            'pacing': 'fast',
            'tone': 'neutral',
            'paragraph_length': 'short',
            'dialogue_ratio': 'medium',
            'cliffhanger_enabled': False,
            'translations': {
                'en': {
                    'name': 'Article Style',
                    'description': 'Journalistic style for news and feature articles',
                    'instructions': '''Write clear, factual, and engaging journalism that informs readers efficiently.

Key elements:
- Lead with the most important information (inverted pyramid structure)
- Use short, punchy paragraphs (typically 2-3 sentences)
- Write clear, concise sentences in active voice
- Present facts objectively without editorial bias
- Include relevant quotes from credible sources
- Provide context and background where necessary
- Use specific details and concrete examples
- Attribute all claims and information to sources
- Maintain professional, accessible tone
- End with additional context or forward-looking perspective
- Follow AP style guidelines for formatting'''
                },
                'zh-hans': {
                    'name': '文章风格',
                    'description': '新闻和专题文章的新闻风格',
                    'instructions': '''撰写清晰、真实和引人入胜的新闻报道，有效地向读者提供信息。

关键要素：
- 以最重要的信息开头（倒金字塔结构）
- 使用简短有力的段落（通常2-3句）
- 用主动语态写清晰简洁的句子
- 客观地呈现事实，不带编辑偏见
- 包括来自可信来源的相关引述
- 在必要时提供背景和背景信息
- 使用具体细节和具体例子
- 将所有声明和信息归因于来源
- 保持专业、易于理解的语气
- 以额外的背景或前瞻性的视角结束
- 遵循AP风格指南进行格式化'''
                }
            }
        }
    ]

    # Create the new styles
    for style_data in styles_data:
        # Create the WritingStyle
        style = WritingStyle.objects.create(
            name_key=style_data['name_key'],
            is_system=True,
            public=True,
            content_type=style_data['content_type'],
            pacing=style_data['pacing'],
            tone=style_data['tone'],
            paragraph_length=style_data['paragraph_length'],
            dialogue_ratio=style_data['dialogue_ratio'],
            cliffhanger_enabled=style_data['cliffhanger_enabled'],
            created_by=None
        )

        # Create translations
        for lang_code, trans_data in style_data['translations'].items():
            WritingStyleTranslation.objects.create(
                style=style,
                language_code=lang_code,
                name=trans_data['name'],
                description=trans_data['description'],
                instructions=trans_data['instructions']
            )


def reverse_populate_content_type_styles(apps, schema_editor):
    """Remove the content-type-specific styles."""
    WritingStyle = apps.get_model('novels', 'WritingStyle')

    # Delete the new content-type-specific styles
    WritingStyle.objects.filter(
        name_key__in=['poem', 'essay', 'sketch', 'article']
    ).delete()

    # Revert existing styles back to null content_type
    WritingStyle.objects.filter(is_system=True).update(content_type=None)


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0031_add_content_type_to_writingstyle"),
    ]

    operations = [
        migrations.RunPython(
            populate_content_type_styles,
            reverse_populate_content_type_styles
        ),
    ]
