# Generated by Django 5.0.1 on 2026-01-30 17:37

from django.db import migrations


def consolidate_system_policies(apps, schema_editor):
    """
    Consolidate 5 separate SystemPolicy records into 1 combined record.
    """
    SystemPolicy = apps.get_model('novels', 'SystemPolicy')
    SystemPolicyTranslation = apps.get_model('novels', 'SystemPolicyTranslation')

    # Delete existing 5 policies (translations will cascade)
    SystemPolicy.objects.filter(
        name_key__in=[
            'copyright_policy',
            'output_format_policy',
            'coherence_policy',
            'instruction_following_policy',
            'planning_visibility_policy'
        ]
    ).delete()

    # Create consolidated policy
    consolidated_policy = SystemPolicy.objects.create(
        name_key='system_policy',
        policy_type='combined',
        priority=0,
        is_active=True
    )

    # English consolidated content
    en_content = """Create only original content. Do not plagiarize or copy from existing published works.

Output must be well-formatted narrative prose. Do not include meta-commentary, explanations, or markers unless specifically requested.

Maintain consistency with established world canon, character traits, and plot continuity.

Follow user instructions precisely. If instructions conflict with story logic, prioritize story coherence and inform the user.

Do not reveal internal planning steps or reasoning in the output. Only provide the requested content."""

    # Chinese consolidated content
    zh_content = """仅创作原创内容。不得抄袭或复制现有已发表作品。

输出必须是格式良好的叙事散文。除非明确要求，否则不要包含元评论、解释或标记。

保持与已建立的世界观、角色特质和情节连续性的一致性。

精确遵循用户指示。如果指示与故事逻辑冲突，优先考虑故事连贯性并告知用户。

不要在输出中透露内部规划步骤或推理。仅提供请求的内容。"""

    # Create translations
    SystemPolicyTranslation.objects.create(
        policy=consolidated_policy,
        language_code='en',
        content=en_content
    )

    SystemPolicyTranslation.objects.create(
        policy=consolidated_policy,
        language_code='zh-hans',
        content=zh_content
    )


def reverse_consolidation(apps, schema_editor):
    """Reverse: split back into 5 separate policies."""
    SystemPolicy = apps.get_model('novels', 'SystemPolicy')
    SystemPolicyTranslation = apps.get_model('novels', 'SystemPolicyTranslation')

    # Delete consolidated policy
    SystemPolicy.objects.filter(name_key='system_policy').delete()

    # Recreate the 5 original policies
    policies_data = [
        {
            'name_key': 'copyright_policy',
            'policy_type': 'copyright',
            'priority': 0,
            'translations': {
                'en': 'Create only original content. Do not plagiarize or copy from existing published works.',
                'zh-hans': '仅创作原创内容。不得抄袭或复制现有已发表作品。'
            }
        },
        {
            'name_key': 'output_format_policy',
            'policy_type': 'output',
            'priority': 1,
            'translations': {
                'en': 'Output must be well-formatted narrative prose. Do not include meta-commentary, explanations, or markers unless specifically requested.',
                'zh-hans': '输出必须是格式良好的叙事散文。除非明确要求，否则不要包含元评论、解释或标记。'
            }
        },
        {
            'name_key': 'coherence_policy',
            'policy_type': 'output',
            'priority': 2,
            'translations': {
                'en': 'Maintain consistency with established world canon, character traits, and plot continuity.',
                'zh-hans': '保持与已建立的世界观、角色特质和情节连续性的一致性。'
            }
        },
        {
            'name_key': 'instruction_following_policy',
            'policy_type': 'behavior',
            'priority': 3,
            'translations': {
                'en': 'Follow user instructions precisely. If instructions conflict with story logic, prioritize story coherence and inform the user.',
                'zh-hans': '精确遵循用户指示。如果指示与故事逻辑冲突，优先考虑故事连贯性并告知用户。'
            }
        },
        {
            'name_key': 'planning_visibility_policy',
            'policy_type': 'behavior',
            'priority': 4,
            'translations': {
                'en': 'Do not reveal internal planning steps or reasoning in the output. Only provide the requested content.',
                'zh-hans': '不要在输出中透露内部规划步骤或推理。仅提供请求的内容。'
            }
        }
    ]

    for data in policies_data:
        policy = SystemPolicy.objects.create(
            name_key=data['name_key'],
            policy_type=data['policy_type'],
            priority=data['priority'],
            is_active=True
        )

        for lang_code, content in data['translations'].items():
            SystemPolicyTranslation.objects.create(
                policy=policy,
                language_code=lang_code,
                content=content
            )


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0032_populate_content_type_styles"),
    ]

    operations = [
        migrations.RunPython(
            consolidate_system_policies,
            reverse_consolidation
        ),
    ]
