# Generated by Django 5.0.1 on 2026-01-31 04:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0034_replace_agent_roles_with_content_specific"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstructionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_key",
                    models.CharField(
                        help_text="Unique identifier for this template (e.g., 'poem_instructions')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        help_text="Content type this template is for (poem, essay, sketch, article)",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this template is active"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["content_type", "name_key"],
                "indexes": [
                    models.Index(
                        fields=["content_type"], name="novels_inst_content_4b8723_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="novels_inst_is_acti_7f8b63_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InstructionTemplateTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        choices=[("en", "English"), ("zh-hans", "Simplified Chinese")],
                        max_length=10,
                    ),
                ),
                (
                    "task_description",
                    models.TextField(
                        help_text="Main task description (e.g., 'Write a complete poem based on this theme: {theme}')"
                    ),
                ),
                (
                    "instructions",
                    models.TextField(help_text="Bulleted instructions for the task"),
                ),
                (
                    "json_format",
                    models.TextField(
                        help_text="JSON format specification with example structure"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="novels.instructiontemplate",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["language_code"], name="novels_inst_languag_e57ae3_idx"
                    )
                ],
                "unique_together": {("template", "language_code")},
            },
        ),
    ]
