# Generated by Django 5.0.1 on 2026-01-31 04:17

from django.db import migrations


def populate_instruction_templates(apps, schema_editor):
    """Create instruction templates for all content types with EN + ZH-HANS translations."""
    InstructionTemplate = apps.get_model('novels', 'InstructionTemplate')
    InstructionTemplateTranslation = apps.get_model('novels', 'InstructionTemplateTranslation')

    templates_data = [
        # Poem Instructions
        {
            'name_key': 'poem_instructions',
            'content_type': 'poem',
            'translations': {
                'en': {
                    'task_description': 'Write a complete poem based on this theme: {theme}',
                    'instructions': '''Instructions:
- Create vivid imagery and sensory details
- Pay attention to rhythm and musicality
- Use appropriate poetic form and structure
- Evoke strong emotions
- Target length: approximately {word_count} words''',
                    'json_format': '''Return the poem in JSON format:
{
    "title": "Poem Title",
    "content": "The complete poem text with line breaks"
}'''
                },
                'zh-hans': {
                    'task_description': '基于以下主题创作一首完整的诗歌：{theme}',
                    'instructions': '''说明：
- 创造生动的意象和感官细节
- 注意节奏和音乐性
- 使用适当的诗歌形式和结构
- 唤起强烈的情感
- 目标长度：约 {word_count} 字''',
                    'json_format': '''以 JSON 格式返回诗歌：
{
    "title": "诗歌标题",
    "content": "完整的诗歌文本，带有换行符"
}'''
                }
            }
        },
        # Essay Instructions
        {
            'name_key': 'essay_instructions',
            'content_type': 'essay',
            'translations': {
                'en': {
                    'task_description': 'Write a complete essay with the following thesis: {thesis}',
                    'instructions': '''Instructions:
- Present a clear, compelling thesis
- Build strong arguments with evidence
- Organize with logical flow
- Address potential counterarguments
- Write with clarity and precision
- Target length: approximately {word_count} words''',
                    'json_format': '''Return the essay in JSON format:
{
    "title": "Essay Title",
    "content": "The complete essay text with paragraphs separated by double newlines",
    "sections": {
        "introduction": "...",
        "body1": "...",
        "conclusion": "..."
    }
}'''
                },
                'zh-hans': {
                    'task_description': '撰写一篇完整的论文，论点如下：{thesis}',
                    'instructions': '''说明：
- 提出清晰、有说服力的论点
- 用证据建立有力的论证
- 以逻辑流畅的方式组织
- 处理潜在的反驳论点
- 以清晰和精确的方式写作
- 目标长度：约 {word_count} 字''',
                    'json_format': '''以 JSON 格式返回论文：
{
    "title": "论文标题",
    "content": "完整的论文文本，段落之间用双换行符分隔",
    "sections": {
        "introduction": "...",
        "body1": "...",
        "conclusion": "..."
    }
}'''
                }
            }
        },
        # Sketch Instructions
        {
            'name_key': 'sketch_instructions',
            'content_type': 'sketch',
            'translations': {
                'en': {
                    'task_description': 'Write a literary sketch capturing this observation: {observation}',
                    'instructions': '''Instructions:
- Observe keenly with precise, concrete details
- Use vivid imagery to bring the moment to life
- Reflect thoughtfully on deeper meaning
- Know when to stop - don\'t over-explain
- Target length: approximately {word_count} words''',
                    'json_format': '''Return the sketch in JSON format:
{
    "title": "Sketch Title",
    "content": "The complete sketch text",
    "sections": {
        "moment": "The observed moment...",
        "thought": "Reflection on the moment...",
        "stop": "Final thought or image..."
    }
}'''
                },
                'zh-hans': {
                    'task_description': '撰写一篇文学速写，捕捉以下观察：{observation}',
                    'instructions': '''说明：
- 用精确、具体的细节敏锐地观察
- 使用生动的意象使瞬间栩栩如生
- 深思熟虑地反思更深层的意义
- 知道何时停止 - 不要过度解释
- 目标长度：约 {word_count} 字''',
                    'json_format': '''以 JSON 格式返回速写：
{
    "title": "速写标题",
    "content": "完整的速写文本",
    "sections": {
        "moment": "观察到的时刻...",
        "thought": "对时刻的反思...",
        "stop": "最后的想法或意象..."
    }
}'''
                }
            }
        },
        # Article Instructions
        {
            'name_key': 'article_instructions',
            'content_type': 'article',
            'translations': {
                'en': {
                    'task_description': 'Write a news article with the following headline: {headline}',
                    'instructions': '''Instructions:
- Prioritize accuracy and factual reporting
- Maintain objectivity and balance
- Use clear, concise language
- Present multiple perspectives when relevant
- Follow AP style guidelines
- Target length: approximately {word_count} words''',
                    'json_format': '''Return the article in JSON format:
{
    "title": "Article Headline",
    "content": "The complete article text"
}'''
                },
                'zh-hans': {
                    'task_description': '撰写一篇新闻文章，标题如下：{headline}',
                    'instructions': '''说明：
- 优先考虑准确性和事实报道
- 保持客观性和平衡性
- 使用清晰、简洁的语言
- 在相关时呈现多种观点
- 遵循 AP 风格指南
- 目标长度：约 {word_count} 字''',
                    'json_format': '''以 JSON 格式返回文章：
{
    "title": "文章标题",
    "content": "完整的文章文本"
}'''
                }
            }
        },
    ]

    # Create templates and translations
    for template_data in templates_data:
        # Create the template
        template = InstructionTemplate.objects.create(
            name_key=template_data['name_key'],
            content_type=template_data['content_type'],
            is_active=True
        )

        # Create translations
        for lang_code, trans_data in template_data['translations'].items():
            InstructionTemplateTranslation.objects.create(
                template=template,
                language_code=lang_code,
                task_description=trans_data['task_description'],
                instructions=trans_data['instructions'],
                json_format=trans_data['json_format']
            )


def reverse_populate(apps, schema_editor):
    """Remove all instruction templates."""
    InstructionTemplate = apps.get_model('novels', 'InstructionTemplate')
    InstructionTemplate.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0035_add_instruction_templates"),
    ]

    operations = [
        migrations.RunPython(
            populate_instruction_templates,
            reverse_populate
        ),
    ]
