# Generated by Django 5.0.1 on 2026-01-31 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0036_populate_instruction_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenttypescoringconfig',
            name='default_temperature',
            field=models.DecimalField(decimal_places=1, default=0.7, help_text='Default temperature for OpenAI API calls (0.0-1.2). Higher values = more creative/random.', max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.2)]),
        ),
        migrations.AddField(
            model_name='contenttypescoringconfig',
            name='default_top_p',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='Default top_p for OpenAI API calls (0.3-1.0). Controls diversity via nucleus sampling.', max_digits=2, validators=[django.core.validators.MinValueValidator(0.3), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
