# Generated by Django 5.0.1 on 2026-01-31 05:44

from django.db import migrations
from decimal import Decimal


def populate_temperature_top_p_defaults(apps, schema_editor):
    """Set default temperature and top_p values for each content type."""
    ContentTypeScoringConfig = apps.get_model('novels', 'ContentTypeScoringConfig')

    # Define defaults for each content type
    defaults = {
        'novel': {'temperature': Decimal('0.7'), 'top_p': Decimal('1.0')},
        'poem': {'temperature': Decimal('0.8'), 'top_p': Decimal('1.0')},  # Higher temp for creativity
        'essay': {'temperature': Decimal('0.7'), 'top_p': Decimal('1.0')},
        'sketch': {'temperature': Decimal('0.75'), 'top_p': Decimal('1.0')},
        'article': {'temperature': Decimal('0.3'), 'top_p': Decimal('1.0')},  # Lower temp for factual accuracy
    }

    # Update existing configs
    for content_type, values in defaults.items():
        ContentTypeScoringConfig.objects.filter(content_type=content_type).update(
            default_temperature=values['temperature'],
            default_top_p=values['top_p']
        )


def reverse_populate(apps, schema_editor):
    """Reset temperature and top_p to default values."""
    ContentTypeScoringConfig = apps.get_model('novels', 'ContentTypeScoringConfig')
    ContentTypeScoringConfig.objects.all().update(
        default_temperature=Decimal('0.7'),
        default_top_p=Decimal('1.0')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0037_add_temperature_top_p_to_content_type_config'),
    ]

    operations = [
        migrations.RunPython(
            populate_temperature_top_p_defaults,
            reverse_populate
        ),
    ]
