# Generated by Django 5.0.1 on 2026-01-31 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0038_populate_temperature_top_p_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpiece',
            name='generation_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Temperature used when generating this content (0.0-1.2)', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.2)]),
        ),
        migrations.AddField(
            model_name='contentpiece',
            name='generation_top_p',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Top_p used when generating this content (0.3-1.0)', max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.3), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
