# Generated by Django 5.0.1 on 2026-02-02 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0039_contentpiece_generation_temperature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writingtechnique',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='novelproject',
            name='selected_techniques',
        ),
        migrations.DeleteModel(
            name='WritingTechniqueTranslation',
        ),
        migrations.DeleteModel(
            name='WritingTechnique',
        ),
    ]
