# Generated by Django 5.0.1 on 2026-02-02 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0040_remove_writing_techniques"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agentrole",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this custom role (null for system roles)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_agent_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agentrole",
            name="is_system",
            field=models.BooleanField(
                default=False, help_text="Whether this is a system-defined role"
            ),
        ),
        migrations.AddField(
            model_name="writingstyle",
            name="target_locale",
            field=models.CharField(
                blank=True,
                help_text="Target language for content generation (e.g., 'en', 'zh-hans', 'ja'). When set, overrides user's UI language preference for content generation.",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contentstructuretemplate",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("novel", "Novel"),
                    ("poem", "Poem"),
                    ("essay", "Essay"),
                    ("sketch", "Sketch"),
                    ("article", "News Article"),
                    ("other", "Other - User Specified"),
                ],
                help_text="Type of content this template is for",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contenttypescoringconfig",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("novel", "Novel"),
                    ("poem", "Poem"),
                    ("essay", "Essay"),
                    ("sketch", "Sketch"),
                    ("article", "News Article"),
                    ("other", "Other - User Specified"),
                ],
                help_text="Content type this configuration is for",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="novelproject",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("novel", "Novel"),
                    ("poem", "Poem"),
                    ("essay", "Essay"),
                    ("sketch", "Sketch"),
                    ("article", "News Article"),
                    ("other", "Other - User Specified"),
                ],
                default="novel",
                help_text="Type of content this project will produce",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="agentrole",
            index=models.Index(
                fields=["is_system", "created_by"],
                name="novels_agen_is_syst_1a2841_idx",
            ),
        ),
    ]
