# Generated by Django 5.0.1 on 2026-02-02 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0041_agentrole_created_by_agentrole_is_system_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomWritingStyle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(help_text="Creation time in UNIX timestamp"),
                ),
                (
                    "language_code",
                    models.CharField(
                        help_text="Detected language code (e.g., 'en', 'zh-hans', 'ja')",
                        max_length=10,
                    ),
                ),
                (
                    "style_name",
                    models.CharField(
                        help_text="AI-generated style name", max_length=200
                    ),
                ),
                (
                    "style_instruction",
                    models.TextField(
                        help_text="AI-generated writing style instructions/prompt"
                    ),
                ),
                (
                    "sample",
                    models.TextField(help_text="First 100 words of user's sample text"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this custom style",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_writing_styles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Writing Style",
                "verbose_name_plural": "Custom Writing Styles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="novels_cust_user_id_1c6908_idx",
                    )
                ],
            },
        ),
    ]
