# Generated by Django 5.0.1 on 2026-02-02 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0042_customwritingstyle"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomAgentRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.BigIntegerField(help_text="Creation time in UNIX timestamp"),
                ),
                (
                    "language_code",
                    models.CharField(
                        help_text="Language code (e.g., 'en', 'zh-hans', 'ja')",
                        max_length=10,
                    ),
                ),
                (
                    "role_name",
                    models.CharField(
                        help_text="AI-generated agent role name", max_length=200
                    ),
                ),
                (
                    "role_instruction",
                    models.TextField(
                        help_text="AI-generated agent role instructions/prompt"
                    ),
                ),
                (
                    "custom_style",
                    models.OneToOneField(
                        help_text="Associated custom writing style",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_agent_role",
                        to="novels.customwritingstyle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this custom agent role",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_custom_agent_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Agent Role",
                "verbose_name_plural": "Custom Agent Roles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="novels_cust_user_id_d3c451_idx",
                    )
                ],
            },
        ),
    ]
