# Generated by Django on 2026-02-02

from django.db import migrations


def populate_other_instruction_template(apps, schema_editor):
    """Create instruction template for 'other' content type with EN + ZH-HANS translations."""
    InstructionTemplate = apps.get_model('novels', 'InstructionTemplate')
    InstructionTemplateTranslation = apps.get_model('novels', 'InstructionTemplateTranslation')

    # Check if template already exists
    if InstructionTemplate.objects.filter(name_key='other_instructions').exists():
        return

    template_data = {
        'name_key': 'other_instructions',
        'content_type': 'other',
        'translations': {
            'en': {
                'task_description': 'Generate custom content based on the user requirements',
                'instructions': '''Instructions:
- Follow the specified custom writing style
- Write with clarity and engagement
- Maintain consistent tone and voice
- Target length: approximately {word_count} words''',
                'json_format': '''Return your response in JSON format:
{
    "title": "your title here",
    "content": "your text here"
}'''
            },
            'zh-hans': {
                'task_description': '根据用户要求生成自定义内容',
                'instructions': '''说明：
- 遵循指定的自定义写作风格
- 写作时保持清晰和吸引力
- 保持一致的语气和声音
- 目标长度：约 {word_count} 字''',
                'json_format': '''以 JSON 格式返回您的响应：
{
    "title": "标题",
    "content": "内容"
}'''
            }
        }
    }

    # Create the template
    template = InstructionTemplate.objects.create(
        name_key=template_data['name_key'],
        content_type=template_data['content_type'],
        is_active=True
    )

    # Create translations
    for lang_code, trans_data in template_data['translations'].items():
        InstructionTemplateTranslation.objects.create(
            template=template,
            language_code=lang_code,
            task_description=trans_data['task_description'],
            instructions=trans_data['instructions'],
            json_format=trans_data['json_format']
        )


def reverse_populate(apps, schema_editor):
    """Remove 'other' instruction template."""
    InstructionTemplate = apps.get_model('novels', 'InstructionTemplate')
    InstructionTemplate.objects.filter(name_key='other_instructions').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0043_customagentrole"),
    ]

    operations = [
        migrations.RunPython(
            populate_other_instruction_template,
            reverse_populate
        ),
    ]
