# Generated by Django on 2026-02-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0044_populate_other_instruction_template"),
    ]

    operations = [
        # Step 1: Add model_name field to SystemPolicy (nullable to support existing data)
        migrations.AddField(
            model_name='systempolicy',
            name='model_name',
            field=models.CharField(
                max_length=50,
                blank=True,
                null=True,
                help_text="OpenAI model this policy applies to (e.g., 'gpt-4o-mini', 'gpt-5.2'). "
                          "Leave blank for 'default' policy that applies when no model-specific policy exists."
            ),
        ),

        # Step 2: Add model_name field to AgentRole (nullable to support existing data)
        migrations.AddField(
            model_name='agentrole',
            name='model_name',
            field=models.CharField(
                max_length=50,
                blank=True,
                null=True,
                help_text="OpenAI model this role applies to (e.g., 'gpt-4o-mini', 'gpt-5.2'). "
                          "Leave blank for 'default' role that applies when no model-specific role exists."
            ),
        ),

        # Step 3: Remove unique constraint on name_key for SystemPolicy
        migrations.AlterField(
            model_name='systempolicy',
            name='name_key',
            field=models.CharField(
                max_length=50,
                help_text="Unique identifier for this policy"
            ),
        ),

        # Step 4: Remove unique constraint on name_key for AgentRole
        migrations.AlterField(
            model_name='agentrole',
            name='name_key',
            field=models.CharField(
                max_length=50,
                help_text="Unique identifier for this role"
            ),
        ),

        # Step 5: Add unique_together constraint for SystemPolicy
        migrations.AlterUniqueTogether(
            name='systempolicy',
            unique_together={('name_key', 'model_name')},
        ),

        # Step 6: Add unique_together constraint for AgentRole
        migrations.AlterUniqueTogether(
            name='agentrole',
            unique_together={('name_key', 'model_name')},
        ),

        # Step 7: Add index on model_name for SystemPolicy
        migrations.AddIndex(
            model_name='systempolicy',
            index=models.Index(fields=['is_active', 'priority', 'model_name'], name='novels_syst_is_acti_idx'),
        ),

        # Step 8: Add index on model_name for AgentRole
        migrations.AddIndex(
            model_name='agentrole',
            index=models.Index(fields=['is_active', 'model_name'], name='novels_agen_is_acti_idx'),
        ),
    ]
