# Generated by Django 5.0.1 on 2026-02-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0045_add_model_name_to_policies_and_roles'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='agentrole',
            name='novels_agen_is_acti_78faa0_idx',
        ),
        migrations.RemoveIndex(
            model_name='systempolicy',
            name='novels_syst_is_acti_a7ca2c_idx',
        ),
        migrations.RenameIndex(
            model_name='agentrole',
            new_name='novels_agen_is_acti_1ea67f_idx',
            old_name='novels_agen_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='systempolicy',
            new_name='novels_syst_is_acti_14cd8c_idx',
            old_name='novels_syst_is_acti_idx',
        ),
    ]
