# Generated by Django on 2026-02-03

from django.db import migrations


def populate_and_duplicate_policies_and_roles(apps, schema_editor):
    """
    Update existing SystemPolicy and AgentRole records:
    1. Set model_name='gpt-4o-mini' for all existing records (model_name=NULL)
    2. Duplicate each record with model_name='gpt-5.2'
    """
    SystemPolicy = apps.get_model('novels', 'SystemPolicy')
    SystemPolicyTranslation = apps.get_model('novels', 'SystemPolicyTranslation')
    AgentRole = apps.get_model('novels', 'AgentRole')
    AgentRoleTranslation = apps.get_model('novels', 'AgentRoleTranslation')

    # ========================================
    # Process SystemPolicy records
    # ========================================

    # Get all existing policies (where model_name is NULL)
    existing_policies = SystemPolicy.objects.filter(model_name__isnull=True)

    for policy in existing_policies:
        # Get all translations for this policy
        translations = list(policy.translations.all())

        # Update existing record to gpt-4o-mini
        policy.model_name = 'gpt-4o-mini'
        policy.save()

        # Create duplicate for gpt-5.2
        # First, create the policy object (without saving to get ID)
        gpt5_policy = SystemPolicy.objects.create(
            name_key=policy.name_key,
            policy_type=policy.policy_type,
            model_name='gpt-5.2',
            is_active=policy.is_active,
            priority=policy.priority
        )

        # Duplicate all translations
        for trans in translations:
            SystemPolicyTranslation.objects.create(
                policy=gpt5_policy,
                language_code=trans.language_code,
                content=trans.content  # Same content initially, user will update manually
            )

    # ========================================
    # Process AgentRole records
    # ========================================

    # Get all existing roles (where model_name is NULL)
    existing_roles = AgentRole.objects.filter(model_name__isnull=True)

    for role in existing_roles:
        # Get all translations for this role
        translations = list(role.translations.all())

        # Update existing record to gpt-4o-mini
        role.model_name = 'gpt-4o-mini'
        role.save()

        # Create duplicate for gpt-5.2
        gpt5_role = AgentRole.objects.create(
            name_key=role.name_key,
            module_name=role.module_name,
            model_name='gpt-5.2',
            is_system=role.is_system,
            created_by=role.created_by,
            is_active=role.is_active
        )

        # Duplicate all translations
        for trans in translations:
            AgentRoleTranslation.objects.create(
                role=gpt5_role,
                language_code=trans.language_code,
                system_prompt=trans.system_prompt  # Same content initially, user will update manually
            )


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration:
    1. Delete all gpt-5.2 records
    2. Set gpt-4o-mini records back to NULL
    """
    SystemPolicy = apps.get_model('novels', 'SystemPolicy')
    AgentRole = apps.get_model('novels', 'AgentRole')

    # Delete gpt-5.2 records
    SystemPolicy.objects.filter(model_name='gpt-5.2').delete()
    AgentRole.objects.filter(model_name='gpt-5.2').delete()

    # Set gpt-4o-mini back to NULL
    SystemPolicy.objects.filter(model_name='gpt-4o-mini').update(model_name=None)
    AgentRole.objects.filter(model_name='gpt-4o-mini').update(model_name=None)


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0046_remove_agentrole_novels_agen_is_acti_78faa0_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(
            populate_and_duplicate_policies_and_roles,
            reverse_migration
        ),
    ]
