# Generated by Django 5.0.1 on 2026-02-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0048_add_generation_metadata_to_contentpiece"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_key",
                    models.CharField(
                        help_text="Unique identifier for this prompt template (e.g., 'analyze_simple_style')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Human-readable description of what this template is for",
                        max_length=255,
                    ),
                ),
                (
                    "system_message",
                    models.TextField(
                        help_text="System role message - defines the AI's role and expertise"
                    ),
                ),
                (
                    "developer_message",
                    models.TextField(
                        blank=True,
                        help_text="Developer role message (optional) - additional instructions from developer",
                    ),
                ),
                (
                    "user_message_template",
                    models.TextField(
                        help_text="User prompt template with {placeholders} for dynamic content"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this template is active and should be used",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        help_text="OpenAI model this template applies to (e.g., 'gpt-4o-mini', 'gpt-5.2'). Leave blank for 'default' template that applies when no model-specific template exists.",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Prompt Template",
                "verbose_name_plural": "Prompt Templates",
                "ordering": ["name_key"],
                "indexes": [
                    models.Index(
                        fields=["name_key", "is_active", "model_name"],
                        name="novels_prom_name_ke_22105d_idx",
                    )
                ],
                "unique_together": {("name_key", "model_name")},
            },
        ),
    ]
