# Generated by Django 5.0.1 on 2026-02-04

from django.db import migrations


def populate_analyze_simple_style_prompt(apps, schema_editor):
    """Populate the analyze_simple_style prompt template (English only)."""
    PromptTemplate = apps.get_model('novels', 'PromptTemplate')

    # Create the PromptTemplate with English messages
    PromptTemplate.objects.create(
        name_key='analyze_simple_style',
        description='Analyzes writing samples to extract style definitions and agent roles',
        system_message="You are an expert literary analyst who creates precise writing style definitions and agent role definitions.",
        developer_message="",  # Optional, left empty
        user_message_template="""Analyze the following text sample and generate a custom writing style definition and agent role definition.

Text Sample:
{first_100_words}

Based on this sample, generate:
1. **style_name**: A short, descriptive name for this writing style (e.g., "Poetic Narrative", "Technical Academic", "Conversational Storytelling")
2. **style_instruction**: Detailed instructions for an AI to replicate this writing style. Include specifics about:
   - Sentence structure and rhythm
   - Vocabulary level and word choice
   - Tone and voice
   - Any distinctive stylistic features
3. **agent_role_name**: A short name for the AI agent role that would write in this style (e.g., "Creative Poet", "Academic Scholar", "Casual Storyteller")
4. **agent_role_instruction**: Instructions defining the AI agent's persona, expertise, and approach when writing in this style
5. **language_code**: The language code of the text (e.g., 'en', 'zh-hans', 'zh-hant', 'ja', 'ko', 'fr', 'de', 'es', etc.)

**IMPORTANT INSTRUCTION:**
- Generate ALL text values (`style_name`, `style_instruction`, `agent_role_name`, `agent_role_instruction`) in the SAME LANGUAGE as the text sample above.
- For example: if the sample is in Chinese, write everything in Chinese; if in Japanese, write in Japanese; if in English, write in English.
- The JSON keys must remain in English.
- Only the `language_code` value should be the language code (e.g., 'zh-hans'), not translated.

Return a JSON object with this exact structure:
{{
    "style_name": "name in sample's language",
    "style_instruction": "instructions in sample's language",
    "agent_role_name": "role name in sample's language",
    "agent_role_instruction": "role instructions in sample's language",
    "language_code": "language_code_here"
}}

Return ONLY the JSON object, no additional text.""",
        is_active=True,
        model_name=None  # Default template for all models
    )


def reverse_populate(apps, schema_editor):
    """Remove the analyze_simple_style prompt template."""
    PromptTemplate = apps.get_model('novels', 'PromptTemplate')
    PromptTemplate.objects.filter(name_key='analyze_simple_style').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0049_prompttemplate"),
    ]

    operations = [
        migrations.RunPython(populate_analyze_simple_style_prompt, reverse_populate),
    ]
