# Generated by Django 5.0.1 on 2026-02-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0050_populate_analyze_simple_style_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='customwritingstyle',
            name='temperature',
            field=models.FloatField(default=0.7, help_text='AI-suggested temperature value for this writing style (0.0-1.2)'),
        ),
        migrations.AddField(
            model_name='customwritingstyle',
            name='top_p',
            field=models.FloatField(default=1.0, help_text='AI-suggested top_p value for this writing style (0.0-1.0)'),
        ),
    ]
