# Generated by Django 5.0.1 on 2026-02-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("novels", "0051_add_temperature_top_p_to_custom_writing_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpiece",
            name="video_aspect_ratio",
            field=models.CharField(
                blank=True,
                help_text="Aspect ratio (e.g., '16:9', '9:16', '1:1')",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contentpiece",
            name="video_duration",
            field=models.IntegerField(
                blank=True, help_text="Video duration in seconds (5, 10)", null=True
            ),
        ),
        migrations.AddField(
            model_name="contentpiece",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Generated video file for this content",
                null=True,
                upload_to="generated_videos/",
            ),
        ),
        migrations.AddField(
            model_name="contentpiece",
            name="video_generated_at",
            field=models.DateTimeField(
                blank=True, help_text="When the video was generated", null=True
            ),
        ),
        migrations.AddField(
            model_name="contentpiece",
            name="video_job_id",
            field=models.CharField(
                blank=True,
                help_text="Runway API job ID for tracking async generation",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contentpiece",
            name="video_model",
            field=models.CharField(
                blank=True,
                help_text="Runway model used (e.g., 'gen4-turbo', 'gen4')",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contentpiece",
            name="video_resolution",
            field=models.CharField(
                blank=True,
                help_text="Resolution (e.g., '1280x720', '1920x1080')",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contentpiece",
            name="video_status",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Status: queued, processing, completed, failed",
                max_length=20,
            ),
        ),
    ]
