# Generated by Django 5.0.1 on 2026-02-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0052_contentpiece_video_aspect_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentpiece',
            name='source_image_url',
            field=models.URLField(blank=True, help_text='Source image URL for image-to-video generation', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contentpiece',
            name='source_video_url',
            field=models.URLField(blank=True, help_text='Source video URL for video-to-video generation', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contentpiece',
            name='video_generation_type',
            field=models.CharField(choices=[('text', 'Text to Video'), ('image', 'Image to Video'), ('video', 'Video to Video')], default='text', help_text='Type of video generation method used', max_length=20),
        ),
        migrations.AddField(
            model_name='contentpiece',
            name='video_motion_prompt',
            field=models.TextField(blank=True, help_text='Optional prompt for guiding video generation from media'),
        ),
    ]
