[pytest]
DJANGO_SETTINGS_MODULE = novel_web.settings
python_files = tests.py test_*.py *_tests.py
python_classes = Test*
python_functions = test_*
addopts = --reuse-db --nomigrations -v
testpaths = novels/tests
markers =
    integration: marks tests as integration tests (deselect with '-m "not integration"')
